
services:
  server:
    build:
      context: .
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json


